# Random Forest configuration
name: rf
generation: 2  # intermediate

params:
  n_estimators: 100
  max_depth: null
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: sqrt
  class_weight: balanced
  random_state: ${seed}
  n_jobs: -1

optuna:
  n_trials: 50
  timeout: 7200  # 2 hours
  params:
    n_estimators:
      type: int
      low: 100
      high: 500
      step: 50
    max_depth:
      type: int
      low: 5
      high: 30
      step: 5
    min_samples_split:
      type: int
      low: 2
      high: 20
    min_samples_leaf:
      type: int
      low: 1
      high: 10
    max_features:
      type: categorical
      choices: [sqrt, log2, null]
